language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-baboon' ]; then cd .. && eval "mv $currentfolder generator-baboon" && cd generator-baboon; fi
  - npm install -g grunt-cli
matrix:
  allow_failures:
    - node_js: '0.11'

